# Kester Duncan
# University of South Florida - Computer Science and Engineering
#
# Makefile for creating RImage object
#
# RImage is dependent upon libjpeg 

CC=g++

RImage.o: RImage.cpp RImage.h lib/libjpeg.a
	$(CC) -c RImage.cpp RImage.h lib/libjpeg.a
	
	
	