######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 26 12:37:31 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += remviewer.h
SOURCES += main.cpp remviewer.cpp
